### ISSUE TITLE
DATABASE_URL over database.yml

### ISSUE THREAD

**Issue by bradrobertson** [janko-m/sinatra-activerecord#47]
This is more of an inquiry, but I can submit a PR if you think it'd work.

Right now, sinatra-activerecord [will use database.yml](https://github.com/janko-m/sinatra-activerecord/blob/master/lib/sinatra/activerecord.rb#L20) over DATABASE_URL if it exists, which means we can never override `database.yml` by setting an env var.

This is pretty annoying from a dev/deploy perspective because locally I want to just have a `database.yml` file for simple dev, but when I go to prod, I'd expect `ENV['DATABASE_URL']` to just work, but in fact I get an error because it's looking for a `production` setting in my `database.yml` file.

I propose that we change the order of these lines that checks for the `database.yml` presence and uses it, but then sets the `:database` config to `ENV['DATABASE_URL']` if it exists, to override the yml file.

I can't see this causing any problems for existing projects that rely on `database.yml`, but will make it easier for developers to set a proper URL on their hosted app without having to delete the yml file in order to get things to work.

Thoughts?

**Comment by janko-m** [comment]
You are completely right. I'm pretty sure I thought about it in the past, but I don't know why I've never done anything about it. Yeah, submit the PR. I don't think this will be slightly difficult to test, so you don't have to bother.

**Comment by janko-m** [comment]
Released in the latest version.

**Comment by bradrobertson** [comment]
many thanks :)
