### ISSUE TITLE
db:structure:dump rake task doesn't work with DATABASE_URL

### ISSUE THREAD

**Issue by vorakumar** [janko-m/sinatra-activerecord#52]
When executing db:structure:dump task with DATABASE_URL environment variable, it's failing when looking for 'adapter' configuration. Stack Trace:

```
NoMethodError: undefined method `[]' for nil:NilClass
/Users/kumarvora/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:262:in `block in class_for_adapter'
/Users/kumarvora/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:262:in `each'
```

**Comment by janko-m** [comment]
What is your DATABASE_URL? Does this work in a Rails application? Because I'm basically just reusing tasks from ActiveRecord, so everything that works in Rails should work here.

**Comment by janko-m** [comment]
Ok, I will close this due to inactivity, if you still have the problem, please provide a minimal Sinatra application that reproduces the problem.

**Comment by vincecima** [comment]
From looking at the code inside ActiveRecord, it looks like AR expects the configuration object to be a hash, not a string. This can cause problems when you use DATABASE_URL and database.yml.

**Comment by janko-m** [comment]
Which version of ActiveRecord?
