### ISSUE TITLE
rake db:create fails when using DATABASE_URL environment variable

### ISSUE THREAD

**Issue by cyphactor** [janko-m/sinatra-activerecord#57]
```
$ bundle exec rake db:create                                                          2.2.3 302m fix_sinatra_activerecord_setup e3bdda5 ✗
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "shipmunkapi_dev" does not exist
/Users/adeponte/code/acorns/shipmunk-api/Rakefile:8:in `block (2 levels) in <top (required)>'
PG::ConnectionBad: FATAL:  database "shipmunkapi_dev" does not exist
/Users/adeponte/code/acorns/shipmunk-api/Rakefile:8:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:create => db:load_config
(See full trace by running task with --trace)
```

Turns out after some debugging this is a loading order issue. Specifically, it is line 49 in `lib/sinatra/activerecord.rb`. It looks as follows:

```
ActiveRecord::Base.configurations[environment.to_s] = ActiveRecord::Base.connection.pool.spec.config
```

The way the configuration is obtained, `ActiveRecord::Base.connection.pool.spec.config`, is causing it tell active record to try and obtain a connection. We obviously don't want that in this scenario because the database doesn't exist yet. Also, we probably wouldn't want that in the other scenarios either.

I will dig into ActiveRecord and find a better replacement and submit a pull request.

This is reproducible by following the README instructions except instead of using a `config/database.yml` for local development using the `DATABASE_URL` environment variable. The environment variable mechanisms helps with 12factor apps as well as other apps using the dotenv gem.

**Comment by cyphactor** [comment]
So, after digging through ActiveRecord for a bit I found the following which I believe is a much better mechanism.

```
ActiveRecord::Base.configurations[environment.to_s] = ActiveRecord::ConnectionAdapters::ConnectionSpecification::ConnectionUrlResolver.new(spec).to_hash
```

**Comment by jamesrwhite** [comment]
Closing now https://github.com/janko-m/sinatra-activerecord/pull/58 has been merged.
