### ISSUE TITLE
Searching for a new maintainer

### ISSUE THREAD

**Issue by janko-m** [janko-m/sinatra-activerecord#59]
I'm not using ActiveRecord nor Sinatra anymore, so I wouldn't be able to maintain this gem well anymore. So, I'm looking for a new maintainer, if anyone would like to step in I would be glad to give them commit access.

**Comment by jamesrwhite** [comment]
I'm using this quite heavily in https://github.com/jamesrwhite/minicron so I'd be happy to help out where I can :)

**Comment by janko-m** [comment]
Awesome, I gave you push access. Probably the first thing that would be good to review is https://github.com/janko-m/sinatra-activerecord/pull/58.
