### ISSUE TITLE
Support for Capistrano

### ISSUE THREAD

**Issue by fguillen** [janko-m/sinatra-activerecord#61]
How can I add the capistrano task?

    cap deploy:migrate                 # Runs rake db:migrate if migrations are set

I have tried to add the gem `capistrano-rails` to my Gemfile but it is not working properly because is executing the rake task with `RAILS_ENV` instead of `RACK_ENV`.

**Comment by janko-m** [comment]
In your Capistrano file you can define a task that resembles [the capistrano-rails' one](https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/migrations.rake):

```rb
namespace :deploy do
  task :migrate do
    execute :rake, 'db:migrate'
  end
end
```

You just need to ensure that `RACK_ENV` is set to the appropriate environment before that.

**Comment by fguillen** [comment]
Thanks @janko-m 

In case someone come after me, based on the janko solution, this is what I did:

    # config/deploy/production.rb
    set :rack_env, :production

.

    # config/deploy.rb
    namespace :customs do
      desc "Run Migrations"
      task :migrations do
        on roles(:app) do
          within release_path do
            with rack_env: fetch(:rack_env) do
              execute :rake, "db:migrate"
            end
          end
        end
      end
    end

    # in the proper time, in my case before `after "deploy", "deploy:restart"`
    after "deploy", "customs:migrations"
