### ISSUE TITLE
Published Version Issue

### ISSUE THREAD

**Issue by mkralla11** [janko-m/sinatra-activerecord#70]
I ran into a very unique situation that could potentially reduce a lot problems for other ruby guys who use the latest published gem of sinatra.

**steps to reproduce**:
1. update to the latest version of sinatra (currently 2.0.0.beta2)
2. allow other gems to resolve to the most compatible version, or find out which gems do not support this version yet (bundler should throw an error when running `bundle update`. example of this gem in gemfile: 

```
gem "sinatra", '2.0.0.beta2'
gem sinatra-activerecord (with no version)
```
1. run `bundle update`

**expected result**
this gem should either throw an error like this:

```
could not find compatible versions ...  sinatra-activerecord depends on sinatra (~> 1.0)
```

_OR_
the gem resolves to the most compatible version

**actual result**
sinatra-activerecord gem _falls back to the oldest published version of the gem_: 0.1.3 without you knowing (unless you are keen on knowing every gems' current version).

At this point, if you try to require "sinatra/activerecord" it will fail with a very misleading error:

```
sinatra/activerecord.rb:4:in require':LoadError: cannot load such file -- active_record
```

After digging into the library, you won't realize what has gone wrong until you review the code in the oldest tag of this library's [gemspec](https://github.com/janko-m/sinatra-activerecord/blob/v0.1.3/sinatra-activerecord.gemspec)

which does not specify any activerecord dependency, which is the root cause.

As a final note, I do not expect the maintainer to implement any sort of fix for this, I just want to make it known to anyone who is using the latest version of sinatra whenever this gem is behind supporting the latest release, which at the current time is [~> 1.0](https://github.com/janko-m/sinatra-activerecord/blob/v2.0.11/sinatra-activerecord.gemspec#L22), this exact same thing will happen if you are going through and updating your gems without locking down a version on this specific gem.

**Comment by jayroh** [comment]
This bit me tonight - not knowing why my sinatra 2.0 beta app was not working with AR and sinatra-AR. Turns out pointing to @tomekw's branch certainly does the trick and pulls in the most recent version. If either his branch is merged, or a version of Sinatra in the gemspec is bumped to something allowing the latest beta, then this would be fixed.

@janko-m - what do you think?
