### ISSUE TITLE
Add has_secure_token 

### ISSUE THREAD

**Issue by rvalenciano** [janko-m/sinatra-activerecord#71]
Hi,

Any chance we can have something like [this](https://github.com/rails/rails/pull/18217/commits/5a58ba3366ec6092fcd0e69340acd93f347d2576) in sinatra-activerecord?

I came into a situation where I need exactly that token in the model. I could help adding this to this repo.

Best

**Comment by janko-m** [comment]
@rvalenciano Is there something that prevents you from using `has_secure_token` in sinatra-activerecord?

**Comment by rvalenciano** [comment]
@janko-m , I'm trying to use it and I got NoMethodError: undefined method `has_secure_token' for #<Class:0x007f03c0981578>

The version of the gem I'm using is 2.0.10.

**Comment by janko-m** [comment]
@rvalenciano If calling `has_secure_token` inside your `ActiveRecord::Base` model doesn't work, then you're not using the correct ActiveRecord version. Can you show me where you're calling `has_secure_token`?

**Comment by rvalenciano** [comment]
I have a folder

app/models/my_model.rb

```ruby
class MyModel < ActiveRecord::Base
  has_secure_token
end
```

I've some active record validations in other models in the same folder and they **DO** work (so it's getting ActiveRecord::Base).

**Comment by rvalenciano** [comment]
Updating to 2.0.11 solved, you can close this @janko-m , thanks for your help!
